name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  Weather-daily:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Working'
        env:
          apiID: ${{ secrets.APIID }}
          appSecret: ${{ secrets.APPSECRET }}
          SCKEY: ${{ secrets.SCKEY }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
          WXPUSHER_TOKEN: ${{ secrets.WXPUSHER_TOKEN }}
        run: python weather.py